name = "MilkyCraft Vanilla+"
author = "MilkyJ"
version = "1.9.0-rc2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc72592f73eafe6fba79c3e6f7dcb4843352c4bcfc14285ac10c13ddd6437be7"

[versions]
minecraft = "1.20.1"
forge = "47.4.10"
