name = "MilkyJ Vanilla+"
author = "MilkyJ"
version = "1.8.1-packwiz.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea2ebc0e90ec611eadd2a43c7c0b46ea7d785fdadebd80d96dc3b19ac027bf39"

[versions]
minecraft = "1.20.1"
forge = "47.4.10"
