name = "MilkyJ Vanilla+"
author = "MilkyJ"
version = "1.9.0-rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fbec9e448d53342ea6333fec7bc2aa7ee15ec43a60a5b82ec7f8a54b9b1da14"

[versions]
minecraft = "1.20.1"
forge = "47.4.10"
